const fs=require('fs'),vm=require('vm'),assert=require('assert');const {createCanvas,loadImage}=require('C:/Users/Raisul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const src=fs.readFileSync('game.js','utf8'),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),mix=(a,b,t)=>a+(b-a)*t,ease=t=>{t=clamp(t,0,1);return t*t*(3-2*t)};
const states=[],c={clamp,mix,ease,C:{finale:{danceCycles:1,danceFPS:4,waitLine:'Wait'},boyWalkSpeed:135},phase:'hold',clock:0,total:0,wind:0,V:462,BASE:867,reduce:false,manualPause:false,cinematic:{girl:180,boy:328,boyGait:0},assets:{},meta:{},document:{createElement:()=>createCanvas(1,1)},get:async p=>JSON.parse(fs.readFileSync(p)),image:loadImage,blocked:()=>c.manualPause,$:()=>({textContent:'',style:{}}),askLove(){c.setPhase('loveQuestion');},chime(){},bg:{load(){}},soundSync(){},setPhase(p){states.push(p);c.phase=p;c.clock=0;}};vm.createContext(c);
vm.runInContext(src.slice(src.indexOf('function actorSurface'),src.indexOf('const ready=')),c);
vm.runInContext(src.slice(src.indexOf('function strollDuration'),src.indexOf('function beginCinema')),c);
vm.runInContext(src.slice(src.indexOf('function tick(dt)'),src.indexOf('function makePetal')),c);
vm.runInContext(src.slice(src.indexOf('function romancePhase'),src.indexOf('function drawCinema')),c);
vm.runInContext(src.slice(src.indexOf('function sprite('),src.indexOf('function drawGirl')),c);
vm.runInContext(src.slice(src.indexOf('function glow('),src.indexOf('function sprite(')),c);
(async()=>{await c.loadActor('characters/boy','gentleman');for(const name of ['couple-dance','couple-rise','couple-embrace']){const m=c.meta[name],im=c.assets[name];for(const f of m.frames)assert(f.x+f.w<=im.width&&f.y+f.h<=im.height,name+' bounds');}assert.equal(c.meta['couple-dance'].frames.length,16);assert.equal(c.danceSettings().duration,4);
c.manualPause=true;c.tick(1);assert.equal(c.clock,0);c.manualPause=false;
while(c.phase!=='dance')c.tick(1/60);for(let i=0;i<239;i++)c.tick(1/60);assert.equal(c.phase,'dance');while(c.phase==='dance')c.tick(1/60);while(c.phase!=='loveQuestion')c.tick(1/60);assert.equal(c.romancePose().frame,2);c.setPhase('kiss');while(c.phase!=='wait')c.tick(1/60);assert.deepEqual(states,['danceRise','dance','embrace','loveQuestion','kiss','release','wait']);assert.deepEqual(c.romanceCamera(),{strength:0,zoom:1});while(c.phase!=='cake')c.tick(1/60);assert.deepEqual(states.slice(-5),['walkAway','fetch','return','cakeReveal','cake']);
const out=createCanvas(990,1000),oc=out.getContext('2d'),samples=[['hold',2.5],['danceRise',1.1],['dance',.7],['embrace',1.6],['kiss',2.2],['release',3.15]];c.drawGirl=()=>{};
for(let i=0;i<samples.length;i++){const frame=createCanvas(462,700),ctx=frame.getContext('2d');c.ctx=ctx;[c.phase,c.clock]=samples[i];ctx.fillStyle='#142039';ctx.fillRect(0,0,462,700);ctx.save();ctx.translate(0,-180);c.applyRomanceCamera();c.drawRomance(c.clock);ctx.restore();ctx.fillStyle='#fff';ctx.font='20px sans-serif';ctx.fillText(samples[i][0],18,30);oc.drawImage(frame,i%3*330,Math.floor(i/3)*500,330,500);}
fs.writeFileSync('output/romance-sequence-preview.png',out.toBuffer('image/png'));
const sharp=require('C:/Users/Raisul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');const anim=createCanvas(462,700),ac=anim.getContext('2d'),pages=[];c.ctx=ac;c.phase='dance';
for(let n=0;n<16;n++){c.clock=n/c.danceSettings().fps;ac.fillStyle='#142039';ac.fillRect(0,0,462,700);ac.save();ac.translate(0,-180);c.applyRomanceCamera();c.drawRomance(c.clock);ac.restore();pages.push(Buffer.from(ac.getImageData(0,0,462,700).data));}
await sharp(Buffer.concat(pages),{raw:{width:462,height:700*16,channels:4,pageHeight:700}}).webp({quality:85,loop:0,delay:Array(16).fill(250)}).toFile('output/ballet-motion-preview.webp');
console.log('PASS: 16 dance frames/spin then supported dip, pause freezes time, romance ordering, camera reset, cake continuation, asset bounds; rendered portrait previews');})().catch(e=>{console.error(e);process.exitCode=1});
